services:
  web:
    build:
      context: ./frontend
      target: development
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build: 
      context: ./backend
      target: development
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKDIR_INTERVAL=500